version: '3'
services:
  web:
    image: 'nginx:alpine'
    volumes:
      - './etc/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './etc/ssl:/etc/ssl'
      - './web:/usr/local/www/kosherkaddy.com'
      - './etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template'
      - './etc/nginx/rewriterules:/etc/nginx/includes/rewriterules'
    ports:
      - '8085:80'
      - '4043:443'
      - '8075:81'
    environment:
      - 'NGINX_HOST=${NGINX_HOST}'
    command: >-
      /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template >
      /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - mysqldb
  php:
    build: ./web
    volumes:
      - './etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
      - './web:/usr/local/www/kosherkaddy.com'

  mysqldb:
    build: ./web/mysql-build
    container_name: '${MYSQL_HOST}'
    restart: always

    env_file:
      - .env
    environment:
      - 'MYSQL_HOST=${MYSQL_HOST}'
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
    ports:
      - '7979:3306'
    volumes:
      - './data/db/mysql:/var/lib/mysql:rw,delegated'
      - './etc/mysql/my.cnf:/etc/alternatives/my.cnf'

